sudo: required
services:
  - docker

before_install: 
  - docker build -t v1nc3ntl1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true v1nc3ntl1/react-test npm test

after_success:
  - docker build -t v1nc3ntl1/multi-client ./client
  - docker build -t v1nc3ntl1/multi-nginx ./nginx
  - docker build -t v1nc3ntl1/multi-server ./server
  - docker build -t v1nc3ntl1/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push v1nc3ntl1/multi-client
  - docker push v1nc3ntl1/multi-nginx
  - docker push v1nc3ntl1/multi-server
  - docker push v1nc3ntl1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-640307934110
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY